name       : plank
version    : 0.11.3
release    : 10
source     :
    - https://launchpad.net/plank/1.0/0.11.3/+download/plank-0.11.3.tar.xz : 7f091e3aca4b13e3507bb573c532973bdf4695289f8d1f095501adbed0f15608
license    : GPL-3.0
component  : desktop.util
summary    : Simple application dock
description: |
    The goal is to provide just what a dock needs and absolutely nothing more. It is, however, a library which can be extended to create other dock programs with more advanced features.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(x11)
    - pkgconfig(libbamf3)
    - vala
setup      : |
    export CFLAGS="$CFLAGS -lm"
    %patch -p1 < $pkgfiles/0001-Change-show-dock-item-default.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/etc
