name       : plank
version    : 0.11.89
release    : 21
source     :
    - https://launchpad.net/plank/1.0/0.11.89/+download/plank-0.11.89.tar.xz : a662a46eaeffbd40661d1f36abd2589f7a98baef4b918876b872047b7ca59d9d
homepage   : https://launchpad.net/plank/
license    : GPL-3.0-or-later
component  : desktop
summary    : Simple application dock
description: |
    The goal is to provide just what a dock needs and absolutely nothing more. It is, however, a library which can be extended to create other dock programs with more advanced features.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(x11)
    - vala
setup      : |
    export CFLAGS="$CFLAGS -lm"
    %apply_patches
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/etc
