name       : plank
version    : 0.10.0
release    : 4
source     :
    - https://launchpad.net/plank/1.0/0.10.0/+download/plank-0.10.0.tar.xz : 4023eaa59cca3ee35032c23c2b011e1cabac812b8828af9ca55e6aaa084ad203
license    : GPL-3.0
clang      : no
summary    : Simple application dock
description: |
    The goal is to provide just what a dock needs and absolutely nothing more. It is, however, a library which can be extended to create other dock programs with more advanced features.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(x11)
    - pkgconfig(libbamf3)
    - vala
setup      : |
    export CFLAGS="$CFLAGS -lm"
    %configure 
build      : |
    %make
install    : |
    %make_install
