name       : plank
version    : 0.11.4
release    : 13
source     :
    - https://launchpad.net/plank/1.0/0.11.4/+download/plank-0.11.4.tar.xz : 88b5cd6a84e67395df5e7cc1869521126830be0e8a509b28ee12e2db0b8981b8
license    : GPL-3.0-or-later
component  : desktop.util
summary    : Simple application dock
description: |
    The goal is to provide just what a dock needs and absolutely nothing more. It is, however, a library which can be extended to create other dock programs with more advanced features.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(x11)
    - vala
setup      : |
    export CFLAGS="$CFLAGS -lm"
    %patch -p1 < $pkgfiles/0001-Change-show-dock-item-default.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/etc
